apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minecraft-${INSTANCE_NAME}-data
  namespace: ${NAMESPACE}
  labels:
    app.kubernetes.io/name: minecraft-bedrock
    app.kubernetes.io/instance: ${INSTANCE_NAME}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: minecraft-${INSTANCE_NAME}
  resources:
    requests:
      storage: ${STORAGE}
  volumeName: minecraft-${INSTANCE_NAME}-pv
